### ISSUE TITLE
babylon demo doesn't enter XR

### ISSUE THREAD

**Issue by jdm** [paulrouget/paulrouget.github.com#2]
There is one call to helper.enterXRAsync in babylon.max.js, and there is a `if (!options.renderTarget) return [3 /*break*/, 4];` right before it. The only key present in `options` when I load http://paulrouget.com/test/bbjs/basic/ in servo is `webXRManagedOutputCanvas`, which comes from https://github.com/paulrouget/paulrouget.github.com/commit/fc4986e2473d79660671041e77bbf8eac9c35e17#diff-8f2a13eb2004a93e39dfeb14a977458cR49.

**Comment by jdm** [comment]
This looks like WebXRDefaultExperience.CreateAsync was updated:
```
return _webXREnterExitUI__WEBPACK_IMPORTED_MODULE_5__["WebXREnterExitUI"].CreateAsync(scene, result.baseExperience, { renderTarget: result.renderTarget }).then(function (ui) {
                    result.enterExitUI = ui;
                });
```
But basic/index.js was not:
```
    // Create ui for entering/exiting xr
    var enterExitUI = await BABYLON.WebXREnterExitUI.CreateAsync(scene, xrHelper, {webXRManagedOutputCanvas: xrOutputCanvas})
```

**Comment by jdm** [comment]
```diff
-    var enterExitUI = await BABYLON.WebXREnterExitUI.CreateAsync(scene, xrHelper, {webXRManagedOutputCanvas: xrOutputCanvas})
+      let renderTarget = xrHelper.sessionManager.getWebXRRenderTarget(xrHelper.onStateChangedObservable);
+      var enterExitUI = await BABYLON.WebXREnterExitUI.CreateAsync(scene, xrHelper, {renderTarget: renderTarget});
```
This change allows entering immersive mode on desktop.

**Comment by paulrouget** [comment]
Thanks. Fixed.
